// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2G9LWmZ-Hi6z0M3arJ5ybebYP9XJz9-Y',
    appId: '1:787009029211:web:5b4084cc7a892fd90f6b7e',
    messagingSenderId: '787009029211',
    projectId: 'auth-bec98',
    authDomain: 'auth-bec98.firebaseapp.com',
    storageBucket: 'auth-bec98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD10Th7uuiPeWe1KTsaieq3eqhMWODoB30',
    appId: '1:787009029211:android:ea5a68263e85e1f90f6b7e',
    messagingSenderId: '787009029211',
    projectId: 'auth-bec98',
    storageBucket: 'auth-bec98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtdn_FtV7xc1RREp5sdY5Fq3xoYBp9aOE',
    appId: '1:787009029211:ios:578bef6b5d908bfa0f6b7e',
    messagingSenderId: '787009029211',
    projectId: 'auth-bec98',
    storageBucket: 'auth-bec98.appspot.com',
    iosClientId:
        '787009029211-u5jm37qo7dfi85ur5b87elgs7555i3hb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtdn_FtV7xc1RREp5sdY5Fq3xoYBp9aOE',
    appId: '1:787009029211:ios:7da63d233c59c45e0f6b7e',
    messagingSenderId: '787009029211',
    projectId: 'auth-bec98',
    storageBucket: 'auth-bec98.appspot.com',
    iosClientId:
        '787009029211-h4lp0idnopfv4fsav8tbbe51v55q4ule.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstpro.RunnerTests',
  );
}
